baseurl: "https://docs.zymbit.com"
disableAliases: true
disableHugoGeneratorInject: true
enableEmoji: true
enableGitInfo: true
enableRobotsTXT: true
languageCode: "en-US"
paginate: 7
rssLimit: 10

theme:
  - docsy
  # - docs-theme

outputs:
  home:
    - HTML
  section:
    - HTML
    - SITEMAP

outputFormats:
  SITEMAP:
    mediaType: application/xml
    baseName: sitemap
    isHTML: false
    isPlainText: true
    noUgly: true
    rel: sitemap

markup:
  tableOfContents:
    startLevel: 2
    endLevel: 4
  goldmark:
    extensions:
      linkify: false
      table: true
    renderer:
      unsafe: true
  highlight:
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: false
    style: monokai
    tabWidth: 4

sitemap:
  changefreq: weekly
  filename: sitemap.xml
  priority: 0.5

taxonomies:
  category: categories
  tag: tags

permalinks:
  docs: "/:sections/:slug/"

module:
  mounts:
    - source: content
      target: content
    - source: assets
      target: assets
    - source: layouts
      target: layouts
    - source: data
      target: data
    - source: static
      target: static
    - source: archetypes
      target: archetypes
      
      
{{ $mid := printf "m-%s" (.RelPermalink | anchorize) }}
{{ $active := eq . $p }}
  {{ if .Params.externalLink }}
    <a class="td-sidebar-link td-sidebar-link__page {{ if and (not $shouldDelayActive) $active }} active{{ end }}" id="{{ $mid }}" href="{{ .Params.externalLink }}">{{ .LinkTitle }}</a>
    {{ $externalLinkOrig := .Params.externalLink }}
    <a class="td-sidebar-link td-sidebar-link__page {{ if and (not $shouldDelayActive) $active }} active{{ end }}" id="{{ $mid }}" href="{{$externalLinkOrig}}" {{ if .Params.externalLinkTitle }}title="{{ .Params.externalLinkTitle }}"{{ end }} {{ if .Params.externalLinkTarget }}target="{{ .Params.externalLinkTarget }}"{{ if eq .Params.externalLinkTarget "_blank" }} rel=noopener {{ end }}{{ end }}>{{ .LinkTitle }}</a>
  {{ else if .Params.externalLinkRelref }}
    {{ $externalLinkOrig := .Params.externalLinkRelref }}
    <a class="td-sidebar-link td-sidebar-link__page {{ if and (not $shouldDelayActive) $active }} active{{ end }}" id="{{ $mid }}" href="{{ relref . $externalLinkOrig }}" {{ if .Params.externalLinkTitle }}title="{{ .Params.externalLinkTitle }}"{{ end }} {{ if .Params.externalLinkTarget }}target="{{ .Params.externalLinkTarget }}"{{ if eq .Params.externalLinkTarget "_blank" }} rel=noopener {{ end }}{{ end }}>{{ .LinkTitle }}</a>
  {{ else }}
    <a class="td-sidebar-link td-sidebar-link__page {{ if and (not $shouldDelayActive) $active }} active{{ end }}" id="{{ $mid }}" href="{{ .RelPermalink }}">{{ .LinkTitle }}</a>
  {{ end }}
