---

main:
  - name: Community
    pre: "<i class=\"fab fa-discourse\"></i>"
    url: https://community.zymbit.com/
    
  - name: Main Sight
    pre: "<i class=\"fab fa-discourse\"></i>"
    url: https://zymbit.com
