mounts:
  - source: content
    target: content
  - source: assets
    target: assets
  - source: layouts
    target: layouts
  - source: data
    target: data
  - source: static
    target: static
  - source: archetypes
    target: archetypes
