# Meta Data for SEO

## Homepage
title = "Zymbit Documentation"
titleSeparator = "|"
titleAddition = "Hardware Security for IoT"
description = ""

## Open Graph + Twitter Cards
images = ["doks.png"]
twitterSite = "zymbit"
twitterCreator = "zymbit"
facebookAuthor = "zymbit"
facebookPublisher = "zymbit"
ogLocale = "en_US"

## JSON-LD
schemaType = "Organization"
schemaLogo = "icon-zymbit.png"
schemaTwitter = "https://twitter.com/zymbit"
schemaLinkedIn = "https://www.linkedin.com/company/zymbit"
schemaGitHub = "https://github.com/zymbit"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"

# Footer
footer = "Powered by <a href=\"https://gohugo.io/\">Hugo</a>."

# Alert
alert = false
alertText = "Like Doks? <a class=\"alert-link\" href=\"https://github.com/h-enk/doks/stargazers\">Star on GitHub</a>. Thanks!</a>"

# Edit Page
docsRepo = "https://github.com/zymbit/docs"
editPage = false
