---

buildFuture: true
buildDrafts: true

caches:
  assets:
    dir: :resourceDir/_gen
    maxAge: 0
  getcsv:
    dir: :cacheDir/:project
    maxAge: 0
  getjson:
    dir: :cacheDir/:project
    maxAge: 0
  images:
    dir: :resourceDir/_gen
    maxAge: 0
  modules:
    dir: :cacheDir/modules
    maxAge: 0
