name: Push Repo to Staging Mirror

on:
  - push
  - delete
  - create
  - workflow_dispatch

jobs:
  mirror-repo:
    runs-on: ubuntu-latest

    steps:
      - name: load ssh private key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.STAGING_DEPLOY_KEY }}
        run: |
          mkdir -p ${HOME}/.ssh

          cp /etc/ssh/ssh_config ${HOME}/.ssh/config || true
          echo -e "Host *\n\tStrictHostKeyChecking no" >> ${HOME}/.ssh/config

          echo "${SSH_PRIVATE_KEY}" > ${HOME}/.ssh/id_rsa
          chmod 600 ${HOME}/.ssh/id_rsa

      # Checkout repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: configure mirror
        env:
          MIRROR_REPO: ${{ secrets.MIRROR_REPO }}
        run: |
          cd ${GITHUB_WORKSPACE}

          git remote add staging "${MIRROR_REPO}"
          git remote remove origin

          git update-ref -d refs/heads/main
          git update-ref -d refs/heads/gh-pages

          git push --prune --force --atomic staging refs/heads/*:refs/upsteream/*
