name: process api docs update

on:
  push:
    branches:
      - "api-docs-update"
  workflow_dispatch:

jobs:
  prepare_hugo_environment:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout the branch with updated API docs
        uses: actions/checkout@v2
        with:
          ref: "api-docs-update"
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.79.1"
          extended: true

      - name: Configure caching for npm
        uses: c-hive/gha-npm-cache@v1

      - name: Install npm dependencies
        run: npm install

      - name: Get updated API doc files
        id: get-doc-files
        run: |
          readarray -t FILE_LIST < <(ls -1A ./content/GENERATED/)

          NEW_FILE_LIST=()

          for api_file in "${FILE_LIST[@]}"; do
            # Determine the location of the new file to generate.
            NEW_FILE=${api_file#GENERATED_}
            NEW_FILE_LIST+=(${NEW_FILE})

            # Remove any old docs with the same name.
            rm -f ./content/api/${NEW_FILE}

            # Generate the frontmatter for the updated docs.
            hugo new api/${NEW_FILE} --kind docs
          done

          echo "::set-output name=new-files::${NEW_FILE_LIST[@]}"
      - name: Generate final doc files
        run: |
          NEW_FILES=(${{ steps.get-doc-files.outputs.new-files }})

          for api_file in "${NEW_FILES[@]}"; do
            echo "New file: ${api_file}"
          done
