name: process api docs update

on:
  push:
    branches:
      - "api-docs-update"
  workflow_dispatch:

jobs:
  prepare_hugo_environment:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout the branch with updated API docs
        uses: actions/checkout@v2
        with:
          ref: "api-docs-update"
          submodules: true
          fetch-depth: 0

      - name: Hugo-ify the API docs
        id: hugoify
        uses: zymbit-docs/actions-hugoify-api-docs@master

      - name: Prepare processed files for commit
        id: prepare-commit
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com

          git add ./content/api/
          git rm -r ./content/GENERATED/

          LAST_COMMIT_MSG=$(git log -1 --grep="^docs" --format="%s" -- content/GENERATED/)
          LAST_HASH=$(expr "$LAST_COMMIT_MSG" : '.* \([0-9a-fA-F]*\)')

          GHA_HUGOIFY_LOG=$(cat .GHA-LOG)
          echo -e "docs: update API docs to latest zkapputils (${LAST_HASH})\n" > .NEW_COMMIT_MSG
          echo -e "${GHA_HUGOIFY_LOG}\n" >> .NEW_COMMIT_MSG
          echo -e "NOTE: THIS COMMIT WAS AUTOMATICALLY GENERATED." >> .NEW_COMMIT_MSG

          git commit --file=.NEW_COMMIT_MSG

          echo -e "::debug::Git log for commit:\n$(git log -1 --pretty=fuller)"

          echo -e "::debug::Git status:\n$(git status)"

          git push origin api-docs-update

      - name: Create pull request
        env:
          GITHUB_TOKEN: ${{ github.token }}
        id: create-pr
        run: |
          gh config set prompt disabled

          echo -e "::debug::GitHub CLI auth status:\n$(gh auth status)"

          gh pr create \
            --base main \
            --draft \
            --fill \
            --head api-docs-update \
            --label "api" --label "automated pr"
